stages:
  - test
  - deploy

before_script:
  - export DATABASE_URL=postgres://postgres:@postgres:5432/python-test-app
  - apt-get update -qy
  - apt-get install -y python-dev python3-pip
  - add-apt-repository universe
  - apt-get install -y chromium-browser
  - pip3 install -r requirements.txt
  - webdrivermanager chrome --linkpath AUTO

test:
  stage: test
  script:
  - python3 -V
  - chromium --version
  - chromedriver --version
  - robot andorra/tests
#
#staging:
#  stage: deploy
#  script:
#  - apt-get update -qy
#  - apt-get install -y ruby-dev
#  - gem install dpl
#  - dpl --provider=heroku --app=gitlab-ci-python-test-staging --api-key=$HEROKU_STAGING_API_KEY
#  only:
#  - master
#
#production:
#  stage: deploy
#  script:
#  - apt-get update -qy
#  - apt-get install -y ruby-dev
#  - gem install dpl
#  - dpl --provider=heroku --app=gitlab-ci-python-test-prod --api-key=$HEROKU_PRODUCTION_API_KEY
#  only:
#  - tags