services:
    - postgres

variables:
    DATABASE_HOST: postgres
    DATABASE_USER: postgres
    DATABASE_PASSWORD: ""

stages:
  - verify
  - deploy
  - test

verify:
  stage: verify
  image: python:3.7
  script:
  - set -xe
  - pip3 install -r requirements_dev.txt
  - flake8
  - python3 -m coverage run manage.py test
  - python3 -m coverage report
  - COVERAGE=$(python3 -m coverage report | tail -n 1 | grep -o "[0-9][0-9]%" | cut -b1,2)
  - if [ $COVERAGE -lt 60 ]; then exit 1; fi

staging:
  stage: deploy
  image: ruby:2.5
  script:
  - gem install dpl
  - dpl --provider=heroku --app=andorra-stg --api-key=$HEROKU_STAGING_API_KEY
  only:
  - master

test:
  stage: test
  image: python:3.7
  script:
  - set -xe
  - apt-get update -qy
  - pip3 install -r requirements_test.txt
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
  - apt-get update -yqqq
  - apt-get install -y google-chrome-stable
  - webdrivermanager chrome --linkpath AUTO
  - python3 -V
  - chromedriver --version
  - google-chrome-stable --version
  - robot --variable URL:http://andorra-stg.herokuapp.com/ --variable BROWSER:chrome tests
  only:
  - master

production:
  stage: deploy
  image: ruby:2.5
  script:
  - gem install dpl
  - dpl --provider=heroku --app=andorra-prod --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
  - tags
