# Generated by Django 3.0.1 on 2020-01-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('skill_points', models.PositiveIntegerField()),
                ('level', models.PositiveSmallIntegerField()),
                ('health_points', models.IntegerField()),
                ('force', models.PositiveIntegerField()),
                ('defense_strength', models.PositiveIntegerField(blank=True, null=True)),
                ('action_points', models.PositiveIntegerField(blank=True, null=True)),
                ('reflex', models.PositiveIntegerField(blank=True, null=True)),
                ('dexterity', models.PositiveIntegerField(blank=True, null=True)),
                ('magic', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
                'ordering': ('name',),
            },
        ),
    ]
