# Generated by Django 3.0.1 on 2020-01-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20200111_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='busy',
            field=models.BooleanField(default=False),
        ),
    ]
