# Generated by Django 3.0.1 on 2020-01-26 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_auto_20200122_1936'),
        ('characters', '0003_character_busy'),
    ]

    operations = [
    ]
