# Generated by Django 3.0.1 on 2020-01-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_merge_20200126_1544'),
        ('characters', '0004_merge_20200124_1733'),
    ]

    operations = [
    ]
