# Generated by Django 3.0.1 on 2020-02-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_auto_20200129_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='growth_points',
            new_name='_growth_points',
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
