# Generated by Django 3.0.1 on 2020-01-21 18:07

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0002_auto_20200120_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='activejourney',
            name='log',
            field=picklefield.fields.PickledObjectField(default='', editable=False),
            preserve_default=False,
        ),
    ]
