# Generated by Django 3.0.1 on 2020-01-21 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0002_activejourney_journey_end'),
        ('journeys', '0003_activejourney_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activejourney',
            name='journey_end',
        ),
    ]
