# Generated by Django 3.0.1 on 2020-01-21 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_character_busy'),
        ('journeys', '0004_merge_20200121_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='activejourney',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='activejourney',
            name='character',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='characters.Character',
                unique=True),
        ),
    ]
