# Generated by Django 3.0.1 on 2020-02-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0006_auto_20200122_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='activejourney',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
