# Generated by Django 3.0.1 on 2020-03-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0008_activejourney_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='activejourney',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
