# Generated by Django 3.0.1 on 2020-01-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('actual_exp', models.PositiveIntegerField()),
                ('next_level_exp', models.PositiveIntegerField()),
                ('level', models.PositiveSmallIntegerField()),
                ('health', models.IntegerField()),
                ('strength', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ('name',),
            },
        ),
    ]
