# Generated by Django 3.0.1 on 2020-01-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='start_training_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
