# Generated by Django 3.0.1 on 2020-02-05 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_auto_20200129_0844'),
        ('training', '0002_auto_20200118_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='character',
            field=models.OneToOneField(blank=True, null=True,
                                       on_delete=django.db.models.deletion.CASCADE, to='characters.Character'),
        ),
        migrations.AddField(
            model_name='training',
            name='end_training_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='is_ending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='training',
            name='number_completed_training',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
